name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publsh node app to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # Checks out to code repository
    - uses: actions/checkout@v4

    - name: Login to Docker Hub with credentials
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to existing docker repo
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: jonahmary17/part3-exercise:latest
